Kind = "caves"
Name = "Caves"
Description = "Dark tunnels carved into the mountainside. Treasures and terrors await within."
Art = "caves.png"
EventsPool = ["test_event"]

[PossibleNeighbours]
forest = 0.2
deep_forest = 0.4
swamps = 0.1
shore = 0.1
caves = 0.2
