Kind = "deep_forest"
Name = "Deep Forest"
Description = "Ancient woods where the canopy blocks all light. Few paths lead out."
Art = "deep_forest.png"
EventsPool = ["test_event"]

[PossibleNeighbours]
forest = 0.5
swamps = 0.2
caves = 0.3
