Kind = "shore"
Name = "Shore"
Description = "A rocky coastline where sea meets land. A good place to make landfall."
Art = "shore.png"
EventsPool = ["cursed_ring_event"]

[PossibleNeighbours]
ocean = 0.1
village = 0.6
monastery = 0.3
forest = 0.6
swamps = 0.6
