Id = "test_event"
Name = "Item test event"
Description = """
There is a weird ring on the ground...
"""

[[OptionDefinitions]]
DisplayText = "Take it"
ResolutionText = "You take the item"
Order = 1
Effects = ["item:cursed_ring"]

[[OptionDefinitions]]
DisplayText = "Don't take it"
ResolutionText = "You think you hear the ring saying \"What a coward\". That's odd, isn't it?"
Order = 2
Conditions = ["honor:5"]
